### ISSUE TITLE
Require Chromium backend

### ISSUE THREAD

**Issue by jiri-janousek** [tiliado/nuvola-app-jupiter-broadcasting#2]
Hello @a-m-s, could you modify the metadata to require the Chromium backend and test it again? I've recently implemented URL filtering for it, so it might break something.

```
"requirements": "Chromium[65] Feature[MSE] Codec[MP3]",
```

**Comment by a-m-s** [comment]
I don't see any new problems.
However, the YouTube embeds are broken with Chromium (and have been since the first time I tried them). The integrate script cannot access the \<video\> tag directly because it's in a cross-site iFrame, and, for some reason, the code I have to enable the YouTube API is broken in Chromium. The player just disappears.
I've not got around to figuring out what's wrong, but it works fine in WebKitGTK.

**Comment by a-m-s** [comment]
Ah, apparently I need "window.onYouTubeIframeAPIReady = blah", in Chromium, where the "window" wasn't needed in WebKitGTK.
I don't see any problems now.

**Comment by a-m-s** [comment]
Done.

**Comment by jiri-janousek** [comment]
> Ah, apparently I need "window.onYouTubeIframeAPIReady = blah", in Chromium, where the "window"  wasn't needed in WebKitGTK.

* There is an extra `function(){}` envelope around each script injected in the Chromium backend.
* I'm quite suprised that your script works on start-up, when it is executed in AppRunner process where `window` is `null` and `window.onYouTubeIframeAPIReady = blah` should produce `TypeError`. I'm reopening this ticket to investigate this further :-) JavaScript never stops suprising me.

**Comment by a-m-s** [comment]
Quite right, it worked fine in a "reload" warm start, but failed in the initial cold start. Fixed now.
